name = "weather-svg"
account_id = "1a5d304db1c315f0731d67e097a1ee6c"
workers_dev = true
compatibility_date = "2024-06-14"

main = "dist/server.js"

kv_namespaces = [
  { binding = "KV_FETCH_CACHE", id = "f1973ac9cc0448599f91354ef38a4e3b" },
]

[build]
command = "pnpm build"
watch_dir = "src"

[dev]
port = 5177

[env.development]
main = "dist/preview.server.js"
kv_namespaces = [
  { binding = "KV_FETCH_CACHE", id = "f1973ac9cc0448599f91354ef38a4e3b" },
]

[env.development.build]
command = "pnpm preview-build"
