name: Deploy to Cloudflare Workers

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: moonrepo/setup-toolchain@v0
        with:
          auto-install: true

      - name: Cache dependencies
        uses: actions/setup-node@v2
        with:
          # `actions/setup-node` can be configured to not set up Node.js by omitting the `node-version` field
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm i

      - name: Deploy using wrangler
        run: pnpm wrangler deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
